# Generated by Django 5.2 on 2025-05-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_studentprofile_user_delete_companyprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=255)),
                ('headquarters_location', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hr_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('availability', models.CharField(max_length=20)),
                ('work_authorization', models.CharField(max_length=50)),
                ('linkedin_url', models.URLField(blank=True, max_length=255)),
                ('github_url', models.URLField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('search_status', models.CharField(default='active', max_length=50)),
                ('preferred_locations', models.CharField(blank=True, max_length=255, null=True)),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='users.user')),
            ],
        ),
    ]
