# Generated by Django 5.2 on 2025-05-05 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='hr_contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='hr_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('energy', 'Energy'), ('manufacturing', 'Manufacturing'), ('entertainment', 'Entertainment'), ('government', 'Government')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Format: XX-XXXXXXX', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_locations',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='search_status',
            field=models.CharField(choices=[('active', 'Actively Searching'), ('passive', 'Open to Opportunities'), ('not_looking', 'Not Looking')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='work_authorization',
            field=models.CharField(choices=[('us_citizen', 'US Citizen'), ('visa', 'Requires Visa Sponsorship'), ('other', 'Other')], max_length=50),
        ),
    ]
