# Generated by Django 5.2 on 2025-05-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_companyprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='work_authorization',
            field=models.CharField(choices=[('us_citizen', 'US Citizen'), ('work_visa', 'Work Visa'), ('student_visa', 'Student Visa (OPT/CPT)'), ('no_sponsorship', 'Requires Sponsorship'), ('other', 'Other')], default='us_citizen', max_length=20),
        ),
    ]
