# Generated by Django 5.2 on 2025-05-08 18:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_studentcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcv',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
