# Generated by Django 5.2 on 2025-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_interview_evaluation_and_more'),
        ('profiles', '0005_studentcv_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='saved_internships',
            field=models.ManyToManyField(blank=True, related_name='saved_internships', to='internships.internship'),
        ),
    ]
