# Generated by Django 5.2 on 2025-05-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverificationtoken_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
