# Generated by Django 5.2 on 2025-05-06 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_studentprofile_user_delete_companyprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
