# Generated by Django 5.2 on 2025-05-08 16:22

import internships.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_embedding'),
        ('profiles', '0003_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='application_deadline',
            field=models.DateField(validators=[internships.validations.validate_future_date]),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='valid_longitude'),
        ),
    ]
