# Generated by Django 5.2 on 2025-05-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_internship_latitude_internship_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_url',
        ),
    ]
