# Generated by Django 5.2 on 2025-05-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_remove_application_resume_url'),
        ('profiles', '0004_studentcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='profiles.studentcv'),
        ),
    ]
